#
# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u8185/extract-files

PRODUCT_COPY_FILES += \
    vendor/huawei/u8185/props/system/lib/hw/lights.msm7k.so:system/lib/hw/lights.msm7k.so \
    vendor/huawei/u8185/props/system/lib/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/u8185/props/system/lib/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/u8185/props/system/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/u8185/props/system/lib/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/huawei/u8185/props/system/lib/hw/gralloc.msm7k.so:system/lib/hw/gralloc.msm7k.so \
    vendor/huawei/u8185/props/system/lib/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/u8185/props/system/lib/hw/copybit.msm7k.so:system/lib/hw/copybit.msm7k.so \

