#
# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u8185/extract-files

PRODUCT_COPY_FILES += \
    vendor/huawei/u8185/props/system/bin/rild:system/bin/rild \
    vendor/huawei/u8185/props/system/bin/qmuxd:system/bin/qmuxd \
    vendor/huawei/u8185/props/system/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/huawei/u8185/props/system/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/u8185/props/system/lib/libshareril.so:system/lib/libshareril.so \
    vendor/huawei/u8185/props/system/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/huawei/u8185/props/system/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/huawei/u8185/props/system/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/huawei/u8185/props/system/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/huawei/u8185/props/system/lib/libcm.so:system/lib/libcm.so \
    vendor/huawei/u8185/props/system/lib/libril.so:system/lib/libril.so \
    vendor/huawei/u8185/props/system/lib/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/huawei/u8185/props/system/lib/libauth.so:system/lib/libauth.so \
    vendor/huawei/u8185/props/system/lib/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/u8185/props/system/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/huawei/u8185/props/system/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/huawei/u8185/props/system/lib/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/u8185/props/system/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/huawei/u8185/props/system/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/huawei/u8185/props/system/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/huawei/u8185/props/system/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/huawei/u8185/props/system/lib/libidl.so:system/lib/libidl.so \
    vendor/huawei/u8185/props/system/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/huawei/u8185/props/system/lib/libgsl.so:system/lib/libgsl.so \
    vendor/huawei/u8185/props/system/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/huawei/u8185/props/system/lib/libdss.so:system/lib/libdss.so \
    vendor/huawei/u8185/props/system/lib/libqdp.so:system/lib/libqdp.so \
    vendor/huawei/u8185/props/system/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/huawei/u8185/props/system/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/huawei/u8185/props/system/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/huawei/u8185/props/system/lib/libnv.so:system/lib/libnv.so \
    vendor/huawei/u8185/props/system/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/u8185/props/system/lib/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/u8185/props/system/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/u8185/props/system/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/huawei/u8185/props/system/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/huawei/u8185/props/system/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/u8185/props/system/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/huawei/u8185/props/system/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/huawei/u8185/props/system/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/huawei/u8185/props/system/lib/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/u8185/props/system/lib/libwms.so:system/lib/libwms.so \

